import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.cdnfonts.com/css/beatrice-display-trial"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: "#ffffff", color: "#111827" }}
      >
        <NavBar />
        <div className="min-h-[60vh]">{children}</div>

        <footer className="w-full bg-[#222222] mt-8 text-[#1f2937]">
          <div className="max-w-6xl mx-auto px-4 py-8">
            <div className="flex flex-col md:flex-row md:justify-between gap-8">
              <div className="md:w-1/3">
                <h4 className="font-semibold text-white text-lg mb-2">Shan Yoma</h4>
                <p className="text-md flex items-start gap-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4 text-pink-400 flex-shrink-0"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="1.5"
                      d="M21 10c0 6-9 13-9 13S3 16 3 10a9 9 0 1118 0z"
                    />
                  </svg>
                  <span className="text-white">Along Johnnie street, Tachileik.</span>
                </p>
                <p className="mt-2 text-md">
                  <a
                    href="tel:09451922223"
                    className="text-pink-400 flex items-center gap-2"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4 text-pink-400"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="1.5"
                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.95.68l1.2 3.6a1 1 0 01-.27 1.02L8.4 11.6a12.07 12.07 0 005 5l1.3-1.3a1 1 0 011.02-.27l3.6 1.2a1 1 0 01.68.95V19a2 2 0 01-2 2H19c-9.39 0-16-6.61-16-16V5z"
                      />
                    </svg>
                    09451922223
                  </a>

                  <a
                    href="tel:09758113774"
                    className="text-pink-400 flex items-center gap-2"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4 text-pink-400"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="1.5"
                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.95.68l1.2 3.6a1 1 0 01-.27 1.02L8.4 11.6a12.07 12.07 0 005 5l1.3-1.3a1 1 0 011.02-.27l3.6 1.2a1 1 0 01.68.95V19a2 2 0 01-2 2H19c-9.39 0-16-6.61-16-16V5z"
                      />
                    </svg>
                    09758113774
                  </a>
                </p>
              </div>

              <div className="md:w-1/3">
                <h4 className="font-semibold text-white text-lg mb-2">Nitchin Pagoda</h4>
                <p className="text-md flex items-start gap-2">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="h-4 w-4 text-pink-400 flex-shrink-0"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth="1.5"
                      d="M21 10c0 6-9 13-9 13S3 16 3 10a9 9 0 1118 0z"
                    />
                  </svg>
                  <span className="text-white">Wunmaing Rd, spanSaing, Tachileik.</span>
                </p>
                <p className="mt-2 text-md">
                  <a
                    href="tel:09451922223"
                    className="text-pink-400 flex items-center gap-2"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4 text-pink-400"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="1.5"
                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.95.68l1.2 3.6a1 1 0 01-.27 1.02L8.4 11.6a12.07 12.07 0 005 5l1.3-1.3a1 1 0 011.02-.27l3.6 1.2a1 1 0 01.68.95V19a2 2 0 01-2 2H19c-9.39 0-16-6.61-16-16V5z"
                      />
                    </svg>
                    09451922223
                  </a>

                  <a
                    href="tel:09758113774"
                    className="text-pink-400 flex items-center gap-2"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-4 w-4 text-pink-400"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        strokeWidth="1.5"
                        d="M3 5a2 2 0 012-2h3.28a1 1 0 01.95.68l1.2 3.6a1 1 0 01-.27 1.02L8.4 11.6a12.07 12.07 0 005 5l1.3-1.3a1 1 0 011.02-.27l3.6 1.2a1 1 0 01.68.95V19a2 2 0 01-2 2H19c-9.39 0-16-6.61-16-16V5z"
                      />
                    </svg>
                    09758113774
                  </a>
                </p>
              </div>

              <div className="md:w-1/3">
                <h4 className="font-semibold text-white text-lg mb-2">Legal</h4>
                <p className="text-md mb-2">
                  <a
                    href="/terms-and-conditions"
                    className="text-pink-400"
                  >
                    Terms &amp; Conditions
                  </a>
                </p>
                <div className="mt-4 flex items-center space-x-3">
                  <a
                    href="#"
                    aria-label="Instagram"
                    className="text-white hover:text-pink-400"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                    >
                      <rect x="3" y="3" width="18" height="18" rx="4" ry="4" />
                      <path d="M16 11.37A4 4 0 1112.63 8 4 4 0 0116 11.37z" />
                      <line x1="17.5" y1="6.5" x2="17.51" y2="6.5" />
                    </svg>
                  </a>
                  <a
                    href="#"
                    aria-label="Facebook"
                    className="text-white hover:text-pink-400"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      viewBox="0 0 24 24"
                      fill="currentColor"
                    >
                      <path d="M22 12a10 10 0 10-11.5 9.9v-7h-2.2V12h2.2V9.8c0-2.2 1.3-3.4 3.3-3.4.95 0 1.95.17 1.95.17v2.1h-1.07c-1.05 0-1.37.65-1.37 1.32V12h2.34l-.37 2.9h-1.97v7A10 10 0 0022 12z" />
                    </svg>
                  </a>
                  <a
                    href="#"
                    aria-label="TikTok"
                    className="text-white hover:text-pink-400"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-5 w-5"
                      viewBox="0 0 24 24"
                      fill="currentColor"
                    >
                      <path d="M9 8v8a4 4 0 104 4V9h2a4 4 0 10-2-1.732V8h-4z" />
                    </svg>
                  </a>
                </div>
              </div>
            </div>

            <div className="mt-6 border-t border-gray-300 pt-4">
              <div className="text-center text-md text-white">
                © 2026 Swe Trendy Hub. All rights reserved.
              </div>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
